// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrustDrop.Common.Database;

#nullable disable

namespace TrustDrop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251108145849_Remove tenant from Tokens")]
    partial class RemovetenantfromTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrustDrop.AccessToken.Models.AccessTokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("access_token_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_deleted_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_token_document_id");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_last_used_at");

                    b.Property<bool>("OneTime")
                        .HasColumnType("boolean")
                        .HasColumnName("access_token_one_time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_token_tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("access_token_hash");

                    b.Property<int>("TtlSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("access_token_ttl_seconds");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_updated_at");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_token_used_count");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("TenantId");

                    b.ToTable("access_token");
                });

            modelBuilder.Entity("TrustDrop.Audit.Models.AuditModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("audit_action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_deleted_at");

                    b.Property<string>("Details")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("audit_details");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_document_id");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("audit_ip");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_updated_at");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("audit_ua");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("TenantId");

                    b.ToTable("audit");
                });

            modelBuilder.Entity("TrustDrop.Auth.Models.RefreshTokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_deleted_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_revoked_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token_tenant_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token_user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "TokenHash" }, "index_refresh_token_token_hash_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "TenantId" }, "index_refresh_token_user_tenant");

                    b.ToTable("refresh_token");
                });

            modelBuilder.Entity("TrustDrop.Document.Models.DocumentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("document_content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_deleted_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_expires_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("document_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("document_name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_owner_id");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_policy_id");

                    b.Property<DateTime?>("ScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_scanned_at");

                    b.Property<decimal>("Size")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("document_size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("document_status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("document_storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("TenantId");

                    b.ToTable("document");
                });

            modelBuilder.Entity("TrustDrop.Policy.Models.PolicyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("AllowedDomain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("policy_allowed_domain");

                    b.Property<Guid?>("AllowedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_allowed_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("policy_created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("policy_deleted_at");

                    b.Property<int?>("MaxDownloads")
                        .HasColumnType("integer")
                        .HasColumnName("policy_max_downloads");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("policy_updated_at");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("policy_valid_until");

                    b.HasKey("Id");

                    b.HasIndex("AllowedUserId");

                    b.HasIndex("TenantId");

                    b.ToTable("policy");
                });

            modelBuilder.Entity("TrustDrop.Tenant.Models.TenantModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tenant_created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tenant_deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tenant_name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_owner_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tenant_updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("tenant");
                });

            modelBuilder.Entity("TrustDrop.User.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_email");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_last_login");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("user_password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("user_role");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea")
                        .HasColumnName("user_salt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "index_user_email_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "index_user_username_unique")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("TrustDrop.User.Models.UserTenantRoleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_tenant_role_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_tenant_role_created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_tenant_role_deleted_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("user_tenant_role_role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_tenant_role_tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_tenant_role_updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_tenant_role_user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique();

                    b.ToTable("user_tenant_role");
                });

            modelBuilder.Entity("TrustDrop.AccessToken.Models.AccessTokenModel", b =>
                {
                    b.HasOne("TrustDrop.Document.Models.DocumentModel", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrustDrop.Tenant.Models.TenantModel", "Tenant")
                        .WithMany("AccessTokens")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TrustDrop.Audit.Models.AuditModel", b =>
                {
                    b.HasOne("TrustDrop.User.Models.UserModel", "Actor")
                        .WithMany("Audits")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrustDrop.Document.Models.DocumentModel", "Document")
                        .WithMany("Audits")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrustDrop.Tenant.Models.TenantModel", "Tenant")
                        .WithMany("Audits")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Document");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TrustDrop.Auth.Models.RefreshTokenModel", b =>
                {
                    b.HasOne("TrustDrop.Tenant.Models.TenantModel", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.HasOne("TrustDrop.User.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrustDrop.Document.Models.DocumentModel", b =>
                {
                    b.HasOne("TrustDrop.User.Models.UserModel", "Owner")
                        .WithMany("Documents")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrustDrop.Policy.Models.PolicyModel", "Policy")
                        .WithMany("Documents")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrustDrop.Tenant.Models.TenantModel", "Tenant")
                        .WithMany("Documents")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Policy");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TrustDrop.Policy.Models.PolicyModel", b =>
                {
                    b.HasOne("TrustDrop.User.Models.UserModel", "AllowedUser")
                        .WithMany()
                        .HasForeignKey("AllowedUserId");

                    b.HasOne("TrustDrop.Tenant.Models.TenantModel", "Tenant")
                        .WithMany("Policies")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllowedUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TrustDrop.Tenant.Models.TenantModel", b =>
                {
                    b.HasOne("TrustDrop.User.Models.UserModel", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TrustDrop.User.Models.UserTenantRoleModel", b =>
                {
                    b.HasOne("TrustDrop.Tenant.Models.TenantModel", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrustDrop.User.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrustDrop.Document.Models.DocumentModel", b =>
                {
                    b.Navigation("Audits");
                });

            modelBuilder.Entity("TrustDrop.Policy.Models.PolicyModel", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TrustDrop.Tenant.Models.TenantModel", b =>
                {
                    b.Navigation("AccessTokens");

                    b.Navigation("Audits");

                    b.Navigation("Documents");

                    b.Navigation("Policies");
                });

            modelBuilder.Entity("TrustDrop.User.Models.UserModel", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
